import { useEffect, useState } from "react";
import { ChevronDown, ChevronUp, Edit3, Plus, Trash2 } from "lucide-react";
import { Empty, Loading, Modal } from "../components/UI";
import { api } from "../lib/api";
import { useToast } from "../context/ToastContext";
import type { Category } from "../types";

export function CategoriesPage() {
  const toast = useToast();
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<Category | null>(null);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({ name: "", icon: "Tag", remark: "" });
  const load = async () => { setLoading(true); try { const result = await api<{ categories: Category[] }>("/categories"); setCategories(result.categories); } catch (e) { toast.error(e instanceof Error ? e.message : "加载失败。"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const open = (category?: Category) => { setEditing(category || null); setForm(category ? { name: category.name, icon: category.icon, remark: category.remark } : { name: "", icon: "Tag", remark: "" }); setShowModal(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { const result = await api<{ message: string }>(editing ? "/categories/" + editing.id : "/categories", { method: editing ? "PATCH" : "POST", body: JSON.stringify(form) }); toast.success(result.message); setEditing(null); setShowModal(false); setForm({ name: "", icon: "Tag", remark: "" }); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : "保存失败。"); } };
  const remove = async (category: Category) => { if (!window.confirm("确定删除分类“" + category.name + "”吗？")) return; try { const result = await api<{ message: string }>("/categories/" + category.id, { method: "DELETE" }); toast.success(result.message); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : "删除失败。"); } };
  const reorder = async (index: number, offset: number) => { const next = [...categories]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setCategories(next); try { await api("/categories/reorder", { method: "PUT", body: JSON.stringify({ items: next.map((item, i) => ({ id: item.id, sortOrder: i + 1 })) }) }); toast.success("分类顺序已保存。"); } catch (e) { toast.error(e instanceof Error ? e.message : "排序失败。"); void load(); } };
  const modalOpen = showModal;
  return <div className="space-y-5"><div className="flex items-end justify-between gap-4"><div><h1 className="page-title">分类管理</h1><p className="page-subtitle">维护商品分类、图标、备注和展示顺序</p></div><button className="btn-primary" onClick={() => open()}><Plus size={18} />新增分类</button></div><section className="card">{loading ? <Loading /> : !categories.length ? <Empty text="暂无分类" /> : <div className="divide-y">{categories.map((category, index) => <div key={category.id} className="flex flex-wrap items-center gap-3 px-5 py-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-lg">🏷️</div><div className="min-w-40 flex-1"><p className="font-semibold">{category.name} <span className="ml-2 text-xs font-normal text-slate-400">{category._count?.products || 0} 件商品</span></p><p className="mt-1 text-sm text-slate-500">{category.remark || "暂无备注"}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-500">{category.icon}</span><div className="flex gap-1"><button className="btn-secondary !p-2" disabled={index === 0} onClick={() => void reorder(index, -1)} title="上移"><ChevronUp size={16} /></button><button className="btn-secondary !p-2" disabled={index === categories.length - 1} onClick={() => void reorder(index, 1)} title="下移"><ChevronDown size={16} /></button><button className="btn-secondary !p-2" onClick={() => open(category)} title="编辑"><Edit3 size={16} /></button><button className="btn-danger !p-2" onClick={() => void remove(category)} title="删除"><Trash2 size={16} /></button></div></div>)}</div>}</section>{modalOpen && <Modal title={editing ? "修改分类" : "新增分类"} onClose={() => { setEditing(null); setShowModal(false); setForm({ name: "", icon: "Tag", remark: "" }); }}><form className="space-y-4 p-5" onSubmit={save}><label><span className="mb-1.5 block text-sm font-medium">分类名称 *</span><input required className="input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span className="mb-1.5 block text-sm font-medium">图标名称</span><input className="input" value={form.icon} onChange={(e) => setForm({ ...form, icon: e.target.value })} placeholder="例如 Tag、Shirt、Package" /><p className="mt-1 text-xs text-slate-400">图标名称用于后续扩展 Lucide 图标映射。</p></label><label><span className="mb-1.5 block text-sm font-medium">备注</span><textarea className="input min-h-24" value={form.remark} onChange={(e) => setForm({ ...form, remark: e.target.value })} /></label><div className="flex justify-end gap-3 border-t pt-4"><button type="button" className="btn-secondary" onClick={() => { setEditing(null); setShowModal(false); setForm({ name: "", icon: "Tag", remark: "" }); }}>取消</button><button className="btn-primary">保存分类</button></div></form></Modal>}</div>;
}
